### ISSUE TITLE
Конвенция именования тестов и тест-кейсов

### ISSUE THREAD

**Issue by nickmarlou** [Acventor/react-tests-setup#2]
Думаю, что нам, чтобы улучшить читаемость кода и избавиться от лишних раздумий о том, как бы описать тест или тест-кейс, будет полезно принять какую-то конвенцию их именования и описать её в `README.MD`.

На эту тему не так много информации.

Я нашёл небольшое обсуждение на [StackOverflow](https://stackoverflow.com/questions/155436/unit-test-naming-best-practices) и несколько вариантов именование тестов на [DZone](https://dzone.com/articles/7-popular-unit-test-naming).

Мне лично нравится 5 вариант и на многих проектах я видел именно что-то подобное:

```js
test('should show modal when click on button', () => {
  userEvent.click(button);
  expect(modal).toBeVisible();
}
```

С именованием тест-кейсов тоже есть вопросы. Вот, например, [стандарты GitLab](https://docs.gitlab.com/ee/development/testing_guide/frontend_testing.html#naming-unit-tests). Они называют тест кейс по имени метода класса, а внутри пишут разные тесты на данный метод. Но тесты могут быть сгруппированы в кейсы по-разному:
- по компонентам
- по redux-экшенам или редьюсерам,
- по функциям-хелперам
- ...

Наверное, для этих целей было бы хорошо иметь пример именования тест-кейсов на каждый из таких случаев.

**Comment by samerset-rmn** [comment]
Согласен, об этом стоит рассказать подробнее. Насчет `should` тоже согласен, мы будем его использовать. Я добавил пулреквест с первым вариантом инструкции на эту тему: https://github.com/Acventor/react-tests-setup/pull/3

**Comment by IvanChokha** [comment]
Для юнит-тестов мне тоже нравится вариант с `Should ... when ...`. Для тест-кейсов думаю будет нормально писать название тестируемого метода / хелпера / компонента и т. д. Вряд ли у нас будут получаться ультра сложные названия.
